function mockDealUpdate() {
  return {
    v: 1,
    matches_filters: { current: [] },
    meta: {
      v: 1,
      action: 'updated',
      object: 'deal',
      id: 2,
      company_id: 7660257,
      user_id: 11685601,
      host: 'limati.pipedrive.com',
      timestamp: 1598307251,
      timestamp_micro: 1598307251233220,
      permitted_user_ids: [11685601],
      trans_pending: false,
      is_bulk_update: false,
      pipedrive_service_name: false,
      matches_filters: { current: [] },
      webhook_id: '230603',
    },
    current: {
      id: Math.floor(Math.random() * 500000000),
      creator_user_id: 11685601,
      user_id: 11685601,
      person_id: 2,
      org_id: 2,
      stage_id: 5,
      title: 'Novo Item',
      value: Math.floor(Math.random() * 10000000),
      currency: 'BRL',
      add_time: '2020-08-24 21:42:32',
      update_time: new Date().toISOString().replace(/T/, ' ').replace(/\..+/, ''),
      stage_change_time: '2020-08-24 21:50:43',
      active: false,
      deleted: false,
      status: 'won',
      probability: null,
      next_activity_date: null,
      next_activity_time: null,
      next_activity_id: null,
      last_activity_id: null,
      last_activity_date: null,
      lost_reason: null,
      visible_to: '3',
      close_time: '2020-08-24 21:50:49',
      pipeline_id: 1,
      won_time: '2020-08-24 21:50:49',
      first_won_time: '2020-08-24 21:50:49',
      lost_time: null,
      products_count: 2,
      files_count: 0,
      notes_count: 0,
      followers_count: 1,
      email_messages_count: 0,
      activities_count: 0,
      done_activities_count: 0,
      undone_activities_count: 0,
      participants_count: 1,
      expected_close_date: null,
      last_incoming_mail_time: null,
      last_outgoing_mail_time: null,
      label: null,
      stage_order_nr: 4,
      person_name: 'Lucas Lima',
      org_name: 'Business Factory',
      next_activity_subject: null,
      next_activity_type: null,
      next_activity_duration: null,
      next_activity_note: null,
      formatted_value: 'R$ 1.220',
      weighted_value: 1220,
      formatted_weighted_value: 'R$ 1.220',
      weighted_value_currency: 'BRL',
      rotten_time: null,
      owner_name: 'Lucas Lima',
      cc_email: 'limati+deal2@pipedrivemail.com',
      org_hidden: false,
      person_hidden: false,
    },
    previous: {
      id: 2,
      creator_user_id: 11685601,
      user_id: 11685601,
      person_id: 2,
      org_id: 2,
      stage_id: 5,
      title: 'Novo Item',
      value: 20,
      currency: 'BRL',
      add_time: '2020-08-24 21:42:32',
      update_time: '2020-08-24 22:06:03',
      stage_change_time: '2020-08-24 21:50:43',
      active: false,
      deleted: false,
      status: 'won',
      probability: null,
      next_activity_date: null,
      next_activity_time: null,
      next_activity_id: null,
      last_activity_id: null,
      last_activity_date: null,
      lost_reason: null,
      visible_to: '3',
      close_time: '2020-08-24 21:50:49',
      pipeline_id: 1,
      won_time: '2020-08-24 21:50:49',
      first_won_time: '2020-08-24 21:50:49',
      lost_time: null,
      products_count: 2,
      files_count: 0,
      notes_count: 0,
      followers_count: 1,
      email_messages_count: 0,
      activities_count: 0,
      done_activities_count: 0,
      undone_activities_count: 0,
      participants_count: 1,
      expected_close_date: null,
      last_incoming_mail_time: null,
      last_outgoing_mail_time: null,
      label: null,
      stage_order_nr: 4,
      person_name: 'Lucas Lima',
      org_name: 'Business Factory',
      next_activity_subject: null,
      next_activity_type: null,
      next_activity_duration: null,
      next_activity_note: null,
      formatted_value: 'R$ 20',
      weighted_value: 20,
      formatted_weighted_value: 'R$ 20',
      weighted_value_currency: 'BRL',
      rotten_time: null,
      owner_name: 'Lucas Lima',
      cc_email: 'limati+deal2@pipedrivemail.com',
      org_hidden: false,
      person_hidden: false,
    },
    event: 'updated.deal',
    retry: 0,
  };
}

module.exports = { mockDealUpdate };
