const dealUpdatedRequestBody = {
  v: 1,
  matches_filters: { current: [] },
  meta: {
    v: 1,
    action: 'updated',
    object: 'deal',
    id: 2,
    company_id: 7660257,
    user_id: 11685601,
    host: 'limati.pipedrive.com',
    timestamp: 1598305353,
    timestamp_micro: 1598305353053000,
    permitted_user_ids: [Array],
    trans_pending: false,
    is_bulk_update: false,
    pipedrive_service_name: false,
    matches_filters: [Object],
    webhook_id: '230603',
  },
  current: {
    id: 2,
    creator_user_id: 11685601,
    user_id: 11685601,
    person_id: 2,
    org_id: 2,
    stage_id: 1,
    title: 'Novo Item',
    value: 0,
    currency: 'BRL',
    add_time: '2020-08-24 21:42:32',
    update_time: '2020-08-24 21:42:33',
    stage_change_time: null,
    active: true,
    deleted: false,
    status: 'open',
    probability: null,
    next_activity_date: null,
    next_activity_time: null,
    next_activity_id: null,
    last_activity_id: null,
    last_activity_date: null,
    lost_reason: null,
    visible_to: '3',
    close_time: null,
    pipeline_id: 1,
    won_time: null,
    first_won_time: null,
    lost_time: null,
    products_count: 0,
    files_count: 0,
    notes_count: 0,
    followers_count: 1,
    email_messages_count: 0,
    activities_count: 0,
    done_activities_count: 0,
    undone_activities_count: 0,
    participants_count: 1,
    expected_close_date: null,
    last_incoming_mail_time: null,
    last_outgoing_mail_time: null,
    label: null,
    stage_order_nr: 0,
    person_name: 'Lucas Lima',
    org_name: 'Business Factory',
    next_activity_subject: null,
    next_activity_type: null,
    next_activity_duration: null,
    next_activity_note: null,
    formatted_value: 'R$ 0',
    weighted_value: 0,
    formatted_weighted_value: 'R$ 0',
    weighted_value_currency: 'BRL',
    rotten_time: null,
    owner_name: 'Lucas Lima',
    cc_email: 'limati+deal2@pipedrivemail.com',
    org_hidden: false,
    person_hidden: false,
    last_activity: null,
    next_activity: null,
  },
  previous: {
    id: 2,
    creator_user_id: 11685601,
    user_id: 11685601,
    person_id: 2,
    org_id: 2,
    stage_id: 1,
    title: 'Novo Item',
    value: 0,
    currency: 'BRL',
    add_time: '2020-08-24 21:42:32',
    update_time: '2020-08-24 21:42:33',
    stage_change_time: null,
    active: true,
    deleted: false,
    status: 'open',
    probability: null,
    next_activity_date: null,
    next_activity_time: null,
    next_activity_id: null,
    last_activity_id: null,
    last_activity_date: null,
    lost_reason: null,
    visible_to: '3',
    close_time: null,
    pipeline_id: 1,
    won_time: null,
    first_won_time: null,
    lost_time: null,
    products_count: 0,
    files_count: 0,
    notes_count: 0,
    followers_count: 0,
    email_messages_count: 0,
    activities_count: 0,
    done_activities_count: 0,
    undone_activities_count: 0,
    participants_count: 1,
    expected_close_date: null,
    last_incoming_mail_time: null,
    last_outgoing_mail_time: null,
    label: null,
    stage_order_nr: 0,
    person_name: 'Lucas Lima',
    org_name: 'Business Factory',
    next_activity_subject: null,
    next_activity_type: null,
    next_activity_duration: null,
    next_activity_note: null,
    formatted_value: 'R$ 0',
    weighted_value: 0,
    formatted_weighted_value: 'R$ 0',
    weighted_value_currency: 'BRL',
    rotten_time: null,
    owner_name: 'Lucas Lima',
    cc_email: 'limati+deal2@pipedrivemail.com',
    org_hidden: false,
    person_hidden: false,
    last_activity: null,
    next_activity: null,
  },
  event: 'updated.deal',
  retry: 0,
};

module.exports = { dealUpdatedRequestBody };
